language: cpp

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9

before_script:
  - export CXX="g++-4.9"

script:
  - make -C Build/linux/gmake config=release_x64
